[custom.all.largest-series-product]
type = "local"
path = "."
ipkg = "largest-series-product.ipkg"
test = "test/test.ipkg"

[custom.all.largest-series-product-test]
type = "local"
path = "test"
ipkg = "test.ipkg"